version: "3.8"

services:
  app:
    container_name: docker-auto-deploy
    image: ${IMAGE_NAME}:${IMAGE_TAG}

    ports:
      - "3000:3000"

    restart: unless-stopped

    environment:
      APP_VERSION: ${IMAGE_TAG}
